# Generated by Django 4.2.1 on 2023-06-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(choices=[('option1', 'Text Classification'), ('option2', 'Translator'), ('option3', 'Text Generation')], max_length=50)),
                ('upload_date', models.DateField()),
                ('background', models.CharField(max_length=5000)),
                ('model_name', models.CharField(max_length=50)),
                ('input_des', models.CharField(max_length=500)),
                ('output_des', models.CharField(max_length=500)),
                ('task_des', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
