# Generated by Django 4.2.1 on 2023-06-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_data',
            field=models.BinaryField(default=b'\x00\x01\x02'),
        ),
        migrations.AddField(
            model_name='model',
            name='tokenizer_data',
            field=models.BinaryField(default=b'\x00\x01\x02'),
        ),
    ]
