# Generated by Django 4.2.1 on 2023-07-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_model_model_data_model_tokenizer_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='model_data',
        ),
        migrations.RemoveField(
            model_name='model',
            name='tokenizer_data',
        ),
    ]
